"""update inquiry model

Revision ID: a355bac21ecd
Revises: 9f1659cfd234
Create Date: 2026-05-24 15:11:31.402512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a355bac21ecd'
down_revision: Union[str, Sequence[str], None] = '9f1659cfd234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.add_column('inquiries', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('inquiries', sa.Column('reply', sa.String(), nullable=True))
    op.add_column('inquiries', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('inquiries_user_id_fkey'), 'inquiries', type_='foreignkey')
    op.create_foreign_key(None, 'inquiries', 'users', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'inquiries', 'users', ['owner_id'], ['id'])
    op.drop_column('inquiries', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.create_foreign_key(op.f('inquiries_user_id_fkey'), 'inquiries', 'users', ['user_id'], ['id'])
    op.drop_column('inquiries', 'is_closed')
    op.drop_column('inquiries', 'reply')
    op.drop_column('inquiries', 'owner_id')
    op.drop_column('inquiries', 'tenant_id')
    # ### end Alembic commands ###
