"""add_address_and_feature_fields_to_boarding_house

Revision ID: be9c9d30894b
Revises: 01e6d42c1f1b
Create Date: 2026-06-10 00:58:38.886136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9c9d30894b'
down_revision: Union[str, Sequence[str], None] = '01e6d42c1f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_unique_constraint(None, 'favorites', ['user_id', 'property_id'])
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'boarding_house_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'boarding_house_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    # ### end Alembic commands ###
