"""add favorites and featured flag

Revision ID: ea8c67c7f3a5
Revises: a355bac21ecd
Create Date: 2026-06-04 02:00:45.666099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8c67c7f3a5'
down_revision: Union[str, Sequence[str], None] = 'a355bac21ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boarding_houses', sa.Column('barangay', sa.String(), nullable=True))
    op.add_column('boarding_houses', sa.Column('city', sa.String(), nullable=True))
    op.add_column('boarding_houses', sa.Column('province', sa.String(), nullable=True))
    op.add_column('boarding_houses', sa.Column('country', sa.String(), nullable=True))
    op.add_column('boarding_houses', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('boarding_houses', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('boarding_houses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('boarding_houses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('boarding_houses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boarding_houses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('boarding_houses', 'updated_at')
    op.drop_column('boarding_houses', 'created_at')
    op.drop_column('boarding_houses', 'is_featured')
    op.drop_column('boarding_houses', 'is_available')
    op.drop_column('boarding_houses', 'country')
    op.drop_column('boarding_houses', 'province')
    op.drop_column('boarding_houses', 'city')
    op.drop_column('boarding_houses', 'barangay')
    # ### end Alembic commands ###
